<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'path_name' => '',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  3 => 
  array (
    'cat_id' => '10',
    'cat_name' => '拍卖保障',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '7',
  ),
  4 => 
  array (
    'cat_id' => '7',
    'cat_name' => '机构支持',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  5 => 
  array (
    'cat_id' => '21',
    'cat_name' => '关于我们',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  6 => 
  array (
    'cat_id' => '8',
    'cat_name' => '新手指南',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '7',
  ),
  7 => 
  array (
    'cat_id' => '9',
    'cat_name' => '支付帮助',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  8 => 
  array (
    'cat_id' => '5',
    'cat_name' => '客户服务 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
);
?>