<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '书法字画',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '38',
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '文玩收藏',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '25',
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => '紫砂陶器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '30',
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '珠宝玉器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '25',
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => '家用电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '26',
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => '家纺家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => '酒类饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '26',
  ),
  7 => 
  array (
    'cat_id' => '8',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => '26',
  ),
);
?>